### ISSUE TITLE
Migration "20231108172804_prop_expression" fails to complete successfully

### ISSUE THREAD

**Issue by willopez** [webstudio-is/webstudio#2632]
When attempting to run all the current migrations, `20231108172804_prop_expression` fails to complete successfully with the error below: 

```
Starting 20231108172804_prop_expression

CHUNK undefined
read: 4.725ms
parse-change: 0.015ms
changedBuilds.length 0

Error:
Invalid `prisma.$executeRawUnsafe()` invocation:


Raw query failed. Code: `N/A`. Message: `error serializing parameter 0: Conversion failed: Couldn't serialize value `Some([])` into a `text`. Value is a list but `text` is not.`
    at Pn.handleRequestError (/home/will/code/seedmail/packages/prisma-client/prisma/migrations/20231108172804_prop_expression/client/runtime/library.js:171:6929)
    at Pn.handleAndLogRequestError (/home/will/code/seedmail/packages/prisma-client/prisma/migrations/20231108172804_prop_expression/client/runtime/library.js:171:6358)
    at Pn.request (/home/will/code/seedmail/packages/prisma-client/prisma/migrations/20231108172804_prop_expression/client/runtime/library.js:171:6237)
    at client.$transaction.timeout (/home/will/code/seedmail/packages/prisma-client/prisma/migrations/20231108172804_prop_expression/migration.ts:194:21)
    at Proxy._transactionWithCallback (/home/will/code/seedmail/packages/prisma-client/prisma/migrations/20231108172804_prop_expression/client/runtime/library.js:174:9307)
    at Module.default (/home/will/code/seedmail/packages/prisma-client/prisma/migrations/20231108172804_prop_expression/migration.ts:66:3)
    at Object.up (/home/will/code/seedmail/packages/prisma-client/migrations-cli/umzug.ts:49:13)
    at <anonymous> (/home/will/code/seedmail/node_modules/umzug/lib/umzug.js:148:21)
    at Umzug.runCommand (/home/will/code/seedmail/node_modules/umzug/lib/umzug.js:107:20)
    at up (/home/will/code/seedmail/packages/prisma-client/migrations-cli/commands.ts:260:5)
```

 OS: Ubuntu
 node: v18.18.2
 pnpm: 8.8.0

**Comment by kof** [comment]
@TrySound might have an idea

**Comment by TrySound** [comment]
Looks like we execute some raw sql which fails when no builds are changed which is always true on clean db. Maybe we need to add a seed with prisms migrations.

cc @istarkov

**Comment by TrySound** [comment]
@willopez @arifluthfi16 you can pull and clear database

**Comment by arifluthfi16** [comment]
worked, thanks a lot!
