### ISSUE TITLE
Environment Variable DATABASE_URL Not Recognized During Prisma Migrations

### ISSUE THREAD

**Issue by bdot-real** [webstudio-is/webstudio#3436]
Attempting to run Prisma migrations fails with the error indicating that the DATABASE_URL environment variable is not found. This issue persists despite correctly setting the environment variable both in the .env file and directly in the shell session.

Environment:

OS: Ubuntu 20.04 LTS
Node.js Version: 20.x
pnpm Version: 9.0.2
PostgreSQL Version: 12
Prisma Version: 5.12.1
Project: Webstudio Builder
Steps to Reproduce:

Provision an AWS Lightsail instance with Ubuntu 20.04 LTS.
Install Node.js 20 and pnpm 9.0.2.
Clone the webstudio-builder repository.
Configure PostgreSQL with a user and database for the application.
Set environment variables in the .env file

BUILDER_HOST=webbuilder.3hl.site
DATABASE_URL=postgresql://webstudio:yourpassword@localhost/webstudio
DIRECT_URL=postgresql://webstudio:yourpassword@localhost/webstudio
DEV_LOGIN=true
AUTH_SECRET=5c8a7b85bce6ece119ee1b8bffeba35a64b07e9ef36b44fec232b45c52f762c2
MAX_ASSETS_PER_PROJECT=50
FILE_UPLOAD_PATH="public/s/uploads"
ASSET_BASE_URL=/s/uploads/

Install dependencies and attempt to run migrations:

pnpm install
export DATABASE_URL=postgresql://webstudio:yourpassword@localhost/webstudio
export DIRECT_URL=postgresql://webstudio:yourpassword@localhost/webstudio
pnpm migrations migrate

Get the following error

PrismaClientInitializationError: error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:17
   | 
16 |   provider = "postgres"
17 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1

Verifying the environment variables in the shell shows they are set correctly.
Manually setting environment variables before running the migration command does not resolve the issue.
The pgcrypto extension is enabled in PostgreSQL.
The .env file is located in the correct directory (/home/ubuntu/webstudio-builder/apps/builder) and contains the correct variables.
The Prisma schema correctly references the DATABASE_URL environment variable.

Log output

ubuntu@ip-172-26-2-180:~/webstudio-builder/apps/builder$ export DATABASE_URL=postgresql://webstudio:yourpassword@localhost/webstudio
ubuntu@ip-172-26-2-180:~/webstudio-builder/apps/builder$ export DIRECT_URL=postgresql://webstudio:yourpassword@localhost/webstudio
ubuntu@ip-172-26-2-180:~/webstudio-builder/apps/builder$ pnpm migrations migrate
There are failed migrations:
  - 20220905153337_noop

PrismaClientInitializationError: error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:17
   | 
16 |   provider = "postgres"
17 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at r (/home/ubuntu/webstudio-builder/packages/prisma-client/prisma/migrations/20220905153337_noop/client/runtime/library.js:112:2493)
    at async xt.transaction (/home/ubuntu/webstudio-builder/packages/prisma-client/prisma/migrations/20220905153337_noop/client/runtime/library.js:111:11894)
    at async Proxy._transactionWithCallback (/home/ubuntu/webstudio-builder/packages/prisma-client/prisma/migrations/20220905153337_noop/client/runtime/library.js:127:9458)
    at Object.up (/home/ubuntu/webstudio-builder/packages/prisma-client/migrations-cli/umzug.ts:49:13)
    at <anonymous> (/home/ubuntu/webstudio-builder/node_modules/.pnpm/umzug@3.2.1/node_modules/umzug/src/umzug.ts:257:6)
    at Umzug.runCommand (/home/ubuntu/webstudio-builder/node_modules/.pnpm/umzug@3.2.1/node_modules/umzug/src/umzug.ts:208:11)
    at up (/home/ubuntu/webstudio-builder/packages/prisma-client/migrations-cli/commands.ts:260:5)
    at Module.migrate (/home/ubuntu/webstudio-builder/packages/prisma-client/migrations-cli/commands.ts:304:3)
    at main (/home/ubuntu/webstudio-builder/packages/prisma-client/migrations-cli/cli.ts:60:5)
    at runMain (/home/ubuntu/webstudio-builder/packages/prisma-client/migrations-cli/cli.ts:105:5)

**Comment by bdot-real** [comment]
Note I can see that is pulling some values from the .env file as I can log in from the dashboard (using the first 4 characters of the secret) but then I get missing databases

**Comment by istarkov** [comment]
We have switched to devcontainers and updated the documentation here: https://docs.webstudio.is/contributing/contributing-for-developers. The changes should now be reflected on the main branch. Issues above should be fixed.
